# Generated by Django 5.1.5 on 2025-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('shift_type', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
