# Generated by Django 5.1.5 on 2025-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(max_length=10),
        ),
    ]
